[package]
name = "sanctum-lst-list"
version = "0.1.0"
edition = "2021"

include = ["README.md", "sanctum-lst-list.toml", "src/"]

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_with = "^3"
solana-program = "^1"
sanctum-macros = "^1"
toml = ">=0.1"
